version: "3.7"

services:

  # bot
  toptop:
    container_name: toptop
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - app-network
    restart: always
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - ./config.ini:/app/config.ini
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        limits:
          cpus: '0.80'

networks:
  app-network:
    driver: bridge